#%RAML 1.0 SecurityScheme
type: Pass Through
description: Client ID and Client Secret authentication

describedBy:
  headers:
    client_id:
      type: string
      required: true
      example: "123456"
    client_secret:
      type: string
      required: true
      example: "abcdef"
  responses:
    401:
      description: Unauthorized
      body:
        application/json:
          example:
            {
              "message": "Invalid or missing client credentials"
            }
