#%RAML 1.0 NamedExample
{
                "id": "101",
                "title": "Meeting Notes",
                "content": "Discuss project timeline.",
                "createdAt": "2025-01-01T09:30:00Z",
                "updatedAt": "2025-01-01T10:45:00Z"
              }