#%RAML 1.0 NamedExample
 {
            "id": "102",
            "title": "ABC",
            "content": "Note Description .........",
            "createdAt": "2025-01-02T10:00:00Z",
            "updatedAt": "2025-01-02T10:05:00Z"
          }